response = client.describe_instances(
    Filters=[
        {
            'Name': 'string',
            'Values': [
                'string',
            ]
        },
    ],
    InstanceIds=[
        'string',
    ],
    DryRun=True | False,
    MaxResults=123,
    NextToken='string'
)

{'Reservations': [{'Groups': [], 'Instances': [
    {'AmiLaunchIndex': 0, 'ImageId': 'ami-0e0f4ff1154834540', 'InstanceId': 'i-0ad13fbee27351183',
     'InstanceType': 'p2.xlarge', 'KeyName': 'mykey',
     'LaunchTime': datetime.datetime(2019, 1, 31, 3, 51, 18, tzinfo=tzutc()), 'Monitoring': {'State': 'disabled'},
     'Placement': {'AvailabilityZone': 'ap-northeast-2c', 'GroupName': '', 'Tenancy': 'default'},
     'PrivateDnsName': 'ip-172-31-18-73.ap-northeast-2.compute.internal', 'PrivateIpAddress': '172.31.18.73',
     'ProductCodes': [], 'PublicDnsName': 'ec2-13-125-242-30.ap-northeast-2.compute.amazonaws.com',
     'PublicIpAddress': '13.125.242.30', 'State': {'Code': 16, 'Name': 'running'}, 'StateTransitionReason': '',
     'SubnetId': 'subnet-4cf5b500', 'VpcId': 'vpc-ba14f6d1', 'Architecture': 'x86_64', 'BlockDeviceMappings': [
        {'DeviceName': '/dev/sda1',
         'Ebs': {'AttachTime': datetime.datetime(2019, 1, 15, 5, 20, 25, tzinfo=tzutc()), 'DeleteOnTermination': True,
                 'Status': 'attached', 'VolumeId': 'vol-00682dd4e111739b8'}}], 'ClientToken': '', 'EbsOptimized': False,
     'EnaSupport': True, 'Hypervisor': 'xen', 'NetworkInterfaces': [{'Association': {'IpOwnerId': 'amazon',
                                                                                     'PublicDnsName': 'ec2-13-125-242-30.ap-northeast-2.compute.amazonaws.com',
                                                                                     'PublicIp': '13.125.242.30'},
                                                                     'Attachment': {
                                                                         'AttachTime': datetime.datetime(2019, 1, 15, 5,
                                                                                                         20, 24,
                                                                                                         tzinfo=tzutc()),
                                                                         'AttachmentId': 'eni-attach-0440ed98f6a94dc27',
                                                                         'DeleteOnTermination': True, 'DeviceIndex': 0,
                                                                         'Status': 'attached'}, 'Description': '',
                                                                     'Groups': [{'GroupName': 'launch-wizard-2',
                                                                                 'GroupId': 'sg-0321134733884b2c7'}],
                                                                     'Ipv6Addresses': [],
                                                                     'MacAddress': '0a:e5:95:7b:b1:2e',
                                                                     'NetworkInterfaceId': 'eni-083de3996294b1885',
                                                                     'OwnerId': '198312547190',
                                                                     'PrivateDnsName': 'ip-172-31-18-73.ap-northeast-2.compute.internal',
                                                                     'PrivateIpAddress': '172.31.18.73',
                                                                     'PrivateIpAddresses': [{'Association': {
                                                                         'IpOwnerId': 'amazon',
                                                                         'PublicDnsName': 'ec2-13-125-242-30.ap-northeast-2.compute.amazonaws.com',
                                                                         'PublicIp': '13.125.242.30'}, 'Primary': True,
                                                                                             'PrivateDnsName': 'ip-172-31-18-73.ap-northeast-2.compute.internal',
                                                                                             'PrivateIpAddress': '172.31.18.73'}],
                                                                     'SourceDestCheck': True, 'Status': 'in-use',
                                                                     'SubnetId': 'subnet-4cf5b500',
                                                                     'VpcId': 'vpc-ba14f6d1'}],
     'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs',
     'SecurityGroups': [{'GroupName': 'launch-wizard-2', 'GroupId': 'sg-0321134733884b2c7'}], 'SourceDestCheck': True,
     'Tags': [{'Key': 'Name', 'Value': 'test_player'}], 'VirtualizationType': 'hvm',
     'CpuOptions': {'CoreCount': 2, 'ThreadsPerCore': 2},
     'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'},
     'HibernationOptions': {'Configured': False}}], 'OwnerId': '198312547190', 'ReservationId': 'r-0211a64bfda42d694'},
                  {'Groups': [], 'Instances': [
                      {'AmiLaunchIndex': 0, 'ImageId': 'ami-06e7b9c5e0c4dd014', 'InstanceId': 'i-0e87c39612d9b4885',
                       'InstanceType': 'm5.xlarge', 'KeyName': 'uxfac_was',
                       'LaunchTime': datetime.datetime(2019, 1, 25, 1, 59, 40, tzinfo=tzutc()),
                       'Monitoring': {'State': 'disabled'},
                       'Placement': {'AvailabilityZone': 'ap-northeast-2a', 'GroupName': '', 'Tenancy': 'default'},
                       'PrivateDnsName': 'ip-172-31-15-49.ap-northeast-2.compute.internal',
                       'PrivateIpAddress': '172.31.15.49', 'ProductCodes': [],
                       'PublicDnsName': 'ec2-13-124-46-224.ap-northeast-2.compute.amazonaws.com',
                       'PublicIpAddress': '13.124.46.224', 'State': {'Code': 16, 'Name': 'running'},
                       'StateTransitionReason': '', 'SubnetId': 'subnet-59b6aa31', 'VpcId': 'vpc-ba14f6d1',
                       'Architecture': 'x86_64', 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {
                          'AttachTime': datetime.datetime(2019, 1, 24, 2, 11, tzinfo=tzutc()),
                          'DeleteOnTermination': True, 'Status': 'attached', 'VolumeId': 'vol-0299e1d946fdbb888'}}],
                       'ClientToken': '', 'EbsOptimized': True, 'EnaSupport': True, 'Hypervisor': 'xen',
                       'NetworkInterfaces': [{'Association': {'IpOwnerId': '198312547190',
                                                              'PublicDnsName': 'ec2-13-124-46-224.ap-northeast-2.compute.amazonaws.com',
                                                              'PublicIp': '13.124.46.224'}, 'Attachment': {
                           'AttachTime': datetime.datetime(2019, 1, 24, 2, 10, 59, tzinfo=tzutc()),
                           'AttachmentId': 'eni-attach-0a2c2050b8d3a9581', 'DeleteOnTermination': True,
                           'DeviceIndex': 0, 'Status': 'attached'}, 'Description': '',
                                              'Groups': [{'GroupName': 'was', 'GroupId': 'sg-0a05c46fba503c338'}],
                                              'Ipv6Addresses': [], 'MacAddress': '02:f8:32:4d:1f:56',
                                              'NetworkInterfaceId': 'eni-0335d080d5c5b5527', 'OwnerId': '198312547190',
                                              'PrivateDnsName': 'ip-172-31-15-49.ap-northeast-2.compute.internal',
                                              'PrivateIpAddress': '172.31.15.49', 'PrivateIpAddresses': [{
                                                                                                             'Association': {
                                                                                                                 'IpOwnerId': '198312547190',
                                                                                                                 'PublicDnsName': 'ec2-13-124-46-224.ap-northeast-2.compute.amazonaws.com',
                                                                                                                 'PublicIp': '13.124.46.224'},
                                                                                                             'Primary': True,
                                                                                                             'PrivateDnsName': 'ip-172-31-15-49.ap-northeast-2.compute.internal',
                                                                                                             'PrivateIpAddress': '172.31.15.49'}],
                                              'SourceDestCheck': True, 'Status': 'in-use',
                                              'SubnetId': 'subnet-59b6aa31', 'VpcId': 'vpc-ba14f6d1'}],
                       'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs',
                       'SecurityGroups': [{'GroupName': 'was', 'GroupId': 'sg-0a05c46fba503c338'}],
                       'SourceDestCheck': True, 'Tags': [{'Key': 'Name', 'Value': 'WasBack'}],
                       'VirtualizationType': 'hvm', 'CpuOptions': {'CoreCount': 2, 'ThreadsPerCore': 2},
                       'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'},
                       'HibernationOptions': {'Configured': False}}], 'OwnerId': '198312547190',
                   'ReservationId': 'r-0bf21bb321eff4d07'}, {'Groups': [], 'Instances': [
        {'AmiLaunchIndex': 0, 'ImageId': 'ami-0c8e4039a99df4618', 'InstanceId': 'i-04c487c57bf41aff7',
         'InstanceType': 'p2.xlarge', 'KeyName': 'gui_instance_key',
         'LaunchTime': datetime.datetime(2019, 1, 23, 8, 19, 15, tzinfo=tzutc()), 'Monitoring': {'State': 'disabled'},
         'Placement': {'AvailabilityZone': 'ap-northeast-2c', 'GroupName': '', 'Tenancy': 'default'},
         'PrivateDnsName': '', 'ProductCodes': [], 'PublicDnsName': '', 'State': {'Code': 48, 'Name': 'terminated'},
         'StateTransitionReason': 'User initiated (2019-01-23 09:52:10 GMT)', 'Architecture': 'x86_64',
         'BlockDeviceMappings': [], 'ClientToken': '', 'EbsOptimized': False, 'EnaSupport': True, 'Hypervisor': 'xen',
         'NetworkInterfaces': [], 'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs', 'SecurityGroups': [],
         'StateReason': {'Code': 'Client.UserInitiatedShutdown',
                         'Message': 'Client.UserInitiatedShutdown: User initiated shutdown'},
         'Tags': [{'Key': 'Name', 'Value': 'make_uxfac_player'}], 'VirtualizationType': 'hvm',
         'CpuOptions': {'CoreCount': 2, 'ThreadsPerCore': 2},
         'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'},
         'HibernationOptions': {'Configured': False}}], 'OwnerId': '198312547190',
                                                             'ReservationId': 'r-01ba20c1d1c4db6c7'}, {'Groups': [],
                                                                                                       'Instances': [{
                                                                                                                         'AmiLaunchIndex': 0,
                                                                                                                         'ImageId': 'ami-0e0f4ff1154834540',
                                                                                                                         'InstanceId': 'i-09efa58437bf8db05',
                                                                                                                         'InstanceType': 'p2.xlarge',
                                                                                                                         'KeyName': 'gui_instance_key',
                                                                                                                         'LaunchTime': datetime.datetime(
                                                                                                                             2019,
                                                                                                                             1,
                                                                                                                             23,
                                                                                                                             8,
                                                                                                                             19,
                                                                                                                             15,
                                                                                                                             tzinfo=tzutc()),
                                                                                                                         'Monitoring': {
                                                                                                                             'State': 'disabled'},
                                                                                                                         'Placement': {
                                                                                                                             'AvailabilityZone': 'ap-northeast-2c',
                                                                                                                             'GroupName': '',
                                                                                                                             'Tenancy': 'default'},
                                                                                                                         'PrivateDnsName': '',
                                                                                                                         'ProductCodes': [],
                                                                                                                         'PublicDnsName': '',
                                                                                                                         'State': {
                                                                                                                             'Code': 48,
                                                                                                                             'Name': 'terminated'},
                                                                                                                         'StateTransitionReason': 'User initiated (2019-01-23 09:52:10 GMT)',
                                                                                                                         'Architecture': 'x86_64',
                                                                                                                         'BlockDeviceMappings': [],
                                                                                                                         'ClientToken': '',
                                                                                                                         'EbsOptimized': False,
                                                                                                                         'EnaSupport': True,
                                                                                                                         'Hypervisor': 'xen',
                                                                                                                         'NetworkInterfaces': [],
                                                                                                                         'RootDeviceName': '/dev/sda1',
                                                                                                                         'RootDeviceType': 'ebs',
                                                                                                                         'SecurityGroups': [],
                                                                                                                         'StateReason': {
                                                                                                                             'Code': 'Client.UserInitiatedShutdown',
                                                                                                                             'Message': 'Client.UserInitiatedShutdown: User initiated shutdown'},
                                                                                                                         'Tags': [
                                                                                                                             {
                                                                                                                                 'Key': 'Name',
                                                                                                                                 'Value': 'make uxfac'}],
                                                                                                                         'VirtualizationType': 'hvm',
                                                                                                                         'CpuOptions': {
                                                                                                                             'CoreCount': 2,
                                                                                                                             'ThreadsPerCore': 2},
                                                                                                                         'HibernationOptions': {
                                                                                                                             'Configured': False}}],
                                                                                                       'OwnerId': '198312547190',
                                                                                                       'ReservationId': 'r-09c755adad796f752'},
                  {'Groups': [], 'Instances': [
                      {'AmiLaunchIndex': 0, 'ImageId': 'ami-0e0f4ff1154834540', 'InstanceId': 'i-00966e6b74465f130',
                       'InstanceType': 'p2.xlarge', 'KeyName': 'mykey',
                       'LaunchTime': datetime.datetime(2019, 1, 31, 3, 51, 25, tzinfo=tzutc()),
                       'Monitoring': {'State': 'disabled'},
                       'Placement': {'AvailabilityZone': 'ap-northeast-2c', 'GroupName': '', 'Tenancy': 'default'},
                       'PrivateDnsName': 'ip-172-31-27-57.ap-northeast-2.compute.internal',
                       'PrivateIpAddress': '172.31.27.57', 'ProductCodes': [],
                       'PublicDnsName': 'ec2-13-125-147-146.ap-northeast-2.compute.amazonaws.com',
                       'PublicIpAddress': '13.125.147.146', 'State': {'Code': 16, 'Name': 'running'},
                       'StateTransitionReason': '', 'SubnetId': 'subnet-4cf5b500', 'VpcId': 'vpc-ba14f6d1',
                       'Architecture': 'x86_64', 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {
                          'AttachTime': datetime.datetime(2019, 1, 25, 9, 29, 51, tzinfo=tzutc()),
                          'DeleteOnTermination': True, 'Status': 'attached', 'VolumeId': 'vol-0f826c3e7f280ec40'}}],
                       'ClientToken': '', 'EbsOptimized': False, 'EnaSupport': True, 'Hypervisor': 'xen',
                       'NetworkInterfaces': [{'Association': {'IpOwnerId': 'amazon',
                                                              'PublicDnsName': 'ec2-13-125-147-146.ap-northeast-2.compute.amazonaws.com',
                                                              'PublicIp': '13.125.147.146'}, 'Attachment': {
                           'AttachTime': datetime.datetime(2019, 1, 25, 9, 29, 50, tzinfo=tzutc()),
                           'AttachmentId': 'eni-attach-07cc856743ebd95b5', 'DeleteOnTermination': True,
                           'DeviceIndex': 0, 'Status': 'attached'}, 'Description': '', 'Groups': [
                           {'GroupName': 'launch-wizard-3', 'GroupId': 'sg-0671528d66ad771e6'}], 'Ipv6Addresses': [],
                                              'MacAddress': '0a:4b:95:08:36:ce',
                                              'NetworkInterfaceId': 'eni-0c27aa9e2c3f94f3b', 'OwnerId': '198312547190',
                                              'PrivateDnsName': 'ip-172-31-27-57.ap-northeast-2.compute.internal',
                                              'PrivateIpAddress': '172.31.27.57', 'PrivateIpAddresses': [{
                                                                                                             'Association': {
                                                                                                                 'IpOwnerId': 'amazon',
                                                                                                                 'PublicDnsName': 'ec2-13-125-147-146.ap-northeast-2.compute.amazonaws.com',
                                                                                                                 'PublicIp': '13.125.147.146'},
                                                                                                             'Primary': True,
                                                                                                             'PrivateDnsName': 'ip-172-31-27-57.ap-northeast-2.compute.internal',
                                                                                                             'PrivateIpAddress': '172.31.27.57'}],
                                              'SourceDestCheck': True, 'Status': 'in-use',
                                              'SubnetId': 'subnet-4cf5b500', 'VpcId': 'vpc-ba14f6d1'}],
                       'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs',
                       'SecurityGroups': [{'GroupName': 'launch-wizard-3', 'GroupId': 'sg-0671528d66ad771e6'}],
                       'SourceDestCheck': True, 'Tags': [{'Key': 'Name', 'Value': 'test_simulator'}],
                       'VirtualizationType': 'hvm', 'CpuOptions': {'CoreCount': 2, 'ThreadsPerCore': 2},
                       'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'},
                       'HibernationOptions': {'Configured': False}}], 'OwnerId': '198312547190',
                   'ReservationId': 'r-0901a525148eede14'}, {'Groups': [], 'Instances': [
        {'AmiLaunchIndex': 0, 'ImageId': 'ami-0c8e4039a99df4618', 'InstanceId': 'i-036c70f9e7ee81d3d',
         'InstanceType': 't3.medium', 'KeyName': 'UxfactoryTestTeam_1',
         'LaunchTime': datetime.datetime(2019, 1, 31, 4, 59, 29, tzinfo=tzutc()), 'Monitoring': {'State': 'disabled'},
         'Placement': {'AvailabilityZone': 'ap-northeast-2c', 'GroupName': '', 'Tenancy': 'default'},
         'PrivateDnsName': '', 'ProductCodes': [], 'PublicDnsName': '', 'State': {'Code': 48, 'Name': 'terminated'},
         'StateTransitionReason': 'User initiated (2019-01-31 05:10:46 GMT)', 'Architecture': 'x86_64',
         'BlockDeviceMappings': [], 'ClientToken': '', 'EbsOptimized': False, 'EnaSupport': True, 'Hypervisor': 'xen',
         'NetworkInterfaces': [], 'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs', 'SecurityGroups': [],
         'StateReason': {'Code': 'Client.UserInitiatedShutdown',
                         'Message': 'Client.UserInitiatedShutdown: User initiated shutdown'},
         'Tags': [{'Key': 'Name', 'Value': 'UxfactoryTestTeam_1 player-cpu'}], 'VirtualizationType': 'hvm',
         'CpuOptions': {'CoreCount': 1, 'ThreadsPerCore': 2}, 'HibernationOptions': {'Configured': False}}],
                                                             'OwnerId': '198312547190',
                                                             'ReservationId': 'r-00aa0a433ccfc8045'}, {'Groups': [],
                                                                                                       'Instances': [{
                                                                                                                         'AmiLaunchIndex': 0,
                                                                                                                         'ImageId': 'ami-0e0f4ff1154834540',
                                                                                                                         'InstanceId': 'i-0c42b7b35dfc56e24',
                                                                                                                         'InstanceType': 'c4.large',
                                                                                                                         'KeyName': 'uxfac_was',
                                                                                                                         'LaunchTime': datetime.datetime(
                                                                                                                             2019,
                                                                                                                             1,
                                                                                                                             21,
                                                                                                                             7,
                                                                                                                             25,
                                                                                                                             27,
                                                                                                                             tzinfo=tzutc()),
                                                                                                                         'Monitoring': {
                                                                                                                             'State': 'disabled'},
                                                                                                                         'Placement': {
                                                                                                                             'AvailabilityZone': 'ap-northeast-2c',
                                                                                                                             'GroupName': '',
                                                                                                                             'Tenancy': 'default'},
                                                                                                                         'PrivateDnsName': 'ip-172-31-18-152.ap-northeast-2.compute.internal',
                                                                                                                         'PrivateIpAddress': '172.31.18.152',
                                                                                                                         'ProductCodes': [],
                                                                                                                         'PublicDnsName': '',
                                                                                                                         'State': {
                                                                                                                             'Code': 80,
                                                                                                                             'Name': 'stopped'},
                                                                                                                         'StateTransitionReason': 'User initiated (2019-01-21 08:49:04 GMT)',
                                                                                                                         'SubnetId': 'subnet-4cf5b500',
                                                                                                                         'VpcId': 'vpc-ba14f6d1',
                                                                                                                         'Architecture': 'x86_64',
                                                                                                                         'BlockDeviceMappings': [
                                                                                                                             {
                                                                                                                                 'DeviceName': '/dev/sda1',
                                                                                                                                 'Ebs': {
                                                                                                                                     'AttachTime': datetime.datetime(
                                                                                                                                         2019,
                                                                                                                                         1,
                                                                                                                                         21,
                                                                                                                                         7,
                                                                                                                                         25,
                                                                                                                                         28,
                                                                                                                                         tzinfo=tzutc()),
                                                                                                                                     'DeleteOnTermination': True,
                                                                                                                                     'Status': 'attached',
                                                                                                                                     'VolumeId': 'vol-0f0438b141143f2d7'}}],
                                                                                                                         'ClientToken': '',
                                                                                                                         'EbsOptimized': True,
                                                                                                                         'EnaSupport': True,
                                                                                                                         'Hypervisor': 'xen',
                                                                                                                         'NetworkInterfaces': [
                                                                                                                             {
                                                                                                                                 'Attachment': {
                                                                                                                                     'AttachTime': datetime.datetime(
                                                                                                                                         2019,
                                                                                                                                         1,
                                                                                                                                         21,
                                                                                                                                         7,
                                                                                                                                         25,
                                                                                                                                         27,
                                                                                                                                         tzinfo=tzutc()),
                                                                                                                                     'AttachmentId': 'eni-attach-07de4ad4b17500672',
                                                                                                                                     'DeleteOnTermination': True,
                                                                                                                                     'DeviceIndex': 0,
                                                                                                                                     'Status': 'attached'},
                                                                                                                                 'Description': '',
                                                                                                                                 'Groups': [
                                                                                                                                     {
                                                                                                                                         'GroupName': 'uxfac_group',
                                                                                                                                         'GroupId': 'sg-0e07d7fcc9bd8ce0e'}],
                                                                                                                                 'Ipv6Addresses': [],
                                                                                                                                 'MacAddress': '0a:d1:7b:02:68:cc',
                                                                                                                                 'NetworkInterfaceId': 'eni-0132fc24ca717772b',
                                                                                                                                 'OwnerId': '198312547190',
                                                                                                                                 'PrivateDnsName': 'ip-172-31-18-152.ap-northeast-2.compute.internal',
                                                                                                                                 'PrivateIpAddress': '172.31.18.152',
                                                                                                                                 'PrivateIpAddresses': [
                                                                                                                                     {
                                                                                                                                         'Primary': True,
                                                                                                                                         'PrivateDnsName': 'ip-172-31-18-152.ap-northeast-2.compute.internal',
                                                                                                                                         'PrivateIpAddress': '172.31.18.152'}],
                                                                                                                                 'SourceDestCheck': True,
                                                                                                                                 'Status': 'in-use',
                                                                                                                                 'SubnetId': 'subnet-4cf5b500',
                                                                                                                                 'VpcId': 'vpc-ba14f6d1'}],
                                                                                                                         'RootDeviceName': '/dev/sda1',
                                                                                                                         'RootDeviceType': 'ebs',
                                                                                                                         'SecurityGroups': [
                                                                                                                             {
                                                                                                                                 'GroupName': 'uxfac_group',
                                                                                                                                 'GroupId': 'sg-0e07d7fcc9bd8ce0e'}],
                                                                                                                         'SourceDestCheck': True,
                                                                                                                         'StateReason': {
                                                                                                                             'Code': 'Client.UserInitiatedShutdown',
                                                                                                                             'Message': 'Client.UserInitiatedShutdown: User initiated shutdown'},
                                                                                                                         'Tags': [
                                                                                                                             {
                                                                                                                                 'Key': 'Name',
                                                                                                                                 'Value': 'WasFront'}],
                                                                                                                         'VirtualizationType': 'hvm',
                                                                                                                         'CpuOptions': {
                                                                                                                             'CoreCount': 1,
                                                                                                                             'ThreadsPerCore': 2},
                                                                                                                         'CapacityReservationSpecification': {
                                                                                                                             'CapacityReservationPreference': 'open'},
                                                                                                                         'HibernationOptions': {
                                                                                                                             'Configured': False}}],
                                                                                                       'OwnerId': '198312547190',
                                                                                                       'ReservationId': 'r-071007da313cbc405'}],
 'ResponseMetadata': {'RequestId': 'ade32e28-a405-4a92-a924-ff5a415f9a24', 'HTTPStatusCode': 200,
                      'HTTPHeaders': {'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked',
                                      'vary': 'Accept-Encoding', 'date': 'Thu, 31 Jan 2019 05:18:02 GMT',
                                      'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
